apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-cont
        image: shubhamthakur143/backend-image:v1
        ports:
        - containerPort: 8080
        env:
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-configmap
              key: db-name
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-configmap
              key: db-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-configmap
              key: db-port
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-username           
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-password
        resources:
          requests:
            cpu: 200m
            memory: 256Mi	
          limits:
            cpu: 500m
            memory: 512Mi
             